"""
IoTHub Full Setup Script
Jalankan: python setup.py

Script ini akan:
1. Setup Supabase connection
2. Setup Netlify Functions
3. Update frontend dengan URL backend
4. Test semua koneksi
"""

import os
import json
import subprocess
import sys

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))

def print_header(text):
    print(f"\n{'='*50}")
    print(f"  {text}")
    print(f"{'='*50}")

def print_step(num, text):
    print(f"\n  [{num}] {text}")

def print_ok(text):
    print(f"  ✅ {text}")

def print_err(text):
    print(f"  ❌ {text}")

def print_info(text):
    print(f"  ℹ️  {text}")

def get_input(prompt, default=""):
    val = input(f"  {prompt}" + (f" [{default}]" if default else "") + ": ").strip()
    return val if val else default

# ============================================
# STEP 1: Setup Environment Variables
# ============================================
def setup_env():
    print_step(1, "Setup Environment Variables")

    env_file = os.path.join(PROJECT_DIR, '.env')

    if os.path.exists(env_file):
        print_info(".env file already exists")
        overwrite = get_input("Overwrite? (y/n)", "n")
        if overwrite.lower() != 'y':
            print_ok("Keeping existing .env")
            return

    print_info("Masukkan credentials dari Supabase & Midtrans:")
    print()

    supabase_url = get_input("Supabase URL", "https://xxxxx.supabase.co")
    supabase_anon = get_input("Supabase Anon Key", "")
    supabase_service = get_input("Supabase Service Key", "")
    midtrans_client = get_input("Midtrans Client Key", "YOUR_MIDTRANS_CLIENT_KEY")
    midtrans_server = get_input("Midtrans Server Key", "YOUR_MIDTRANS_SERVER_KEY")

    # Write .env file
    env_content = f"""# IoTHub Environment Variables
# Generated by setup.py

# Supabase
SUPABASE_URL={supabase_url}
SUPABASE_ANON_KEY={supabase_anon}
SUPABASE_SERVICE_KEY={supabase_service}

# Midtrans
MIDTRANS_CLIENT_KEY={midtrans_client}
MIDTRANS_SERVER_KEY={midtrans_server}
MIDTRANS_IS_PRODUCTION=false

# Netlify
SITE_NAME=iothub
"""

    with open(env_file, 'w') as f:
        f.write(env_content)

    print_ok(f"Created .env file")

    # Also create netlify environment
    netlify_env = os.path.join(PROJECT_DIR, '.env.production')
    with open(netlify_env, 'w') as f:
        f.write(env_content)

    print_ok("Created .env.production for Netlify")

    return {
        'supabase_url': supabase_url,
        'supabase_anon': supabase_anon,
        'supabase_service': supabase_service,
        'midtrans_client': midtrans_client,
        'midtrans_server': midtrans_server
    }


# ============================================
# STEP 2: Create Netlify Functions
# ============================================
def create_netlify_functions():
    print_step(2, "Create Netlify Functions")

    functions_dir = os.path.join(PROJECT_DIR, 'netlify', 'functions')

    # Create-supabase-auth function
    auth_code = '''
import json
import os
import hashlib
import secrets
import time
from urllib.request import Request, urlopen
from urllib.error import HTTPError

SUPABASE_URL = os.environ.get('SUPABASE_URL', '')
SUPABASE_KEY = os.environ.get('SUPABASE_SERVICE_KEY', '')

def supabase_request(endpoint, method='GET', data=None):
    url = f"{SUPABASE_URL}/rest/v1/{endpoint}"
    headers = {
        'apikey': SUPABASE_KEY,
        'Authorization': f'Bearer {SUPABASE_KEY}',
        'Content-Type': 'application/json',
        'Prefer': 'return=representation'
    }
    body = json.dumps(data).encode() if data else None
    req = Request(url, data=body, headers=headers, method=method)
    with urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode())

def handler(event, context):
    if event['httpMethod'] == 'OPTIONS':
        return {"statusCode": 200, "headers": {"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "Content-Type", "Access-Control-Allow-Methods": "POST, OPTIONS"}, "body": ""}

    if event['httpMethod'] != 'POST':
        return {"statusCode": 405, "body": json.dumps({"error": "Method not allowed"})}

    try:
        body = json.loads(event['body'])
        action = body.get('action', '')

        if action == 'register':
            email = body.get('email', '').strip()
            name = body.get('name', '').strip()
            password = body.get('password', '')

            if not email or not name or len(password) < 8:
                return {"statusCode": 400, "body": json.dumps({"error": "Data tidak valid. Password minimal 8 karakter."})}

            # Check if email exists
            existing = supabase_request(f"users?email=eq.{email}&select=id")
            if existing:
                return {"statusCode": 400, "body": json.dumps({"error": "Email sudah terdaftar"})}

            # Hash password with PBKDF2
            salt = secrets.token_hex(16)
            pw_hash = hashlib.pbkdf2_hmac('sha256', password.encode(), salt.encode(), 100000).hex()

            # Create user
            user = supabase_request("users", "POST", {
                "email": email, "name": name, "password_hash": f"{salt}:{pw_hash}",
                "plan": "free", "is_active": True
            })

            if user:
                token = secrets.token_hex(32)
                supabase_request("sessions", "POST", {
                    "user_id": user[0]['id'], "token": token,
                    "expires_at": time.strftime("%Y-%m-%dT%H:%M:%S+00:00", time.gmtime(time.time()+86400))
                })
                return {"statusCode": 200, "headers": {"Access-Control-Allow-Origin": "*"}, "body": json.dumps({
                    "success": True, "token": token,
                    "user": {"email": email, "name": name, "plan": "free"}
                })}

            return {"statusCode": 500, "body": json.dumps({"error": "Gagal membuat akun"})}

        elif action == 'login':
            email = body.get('email', '').strip()
            password = body.get('password', '')

            users = supabase_request(f"users?email=eq.{email}&select=id,email,name,password_hash,plan")
            if not users:
                return {"statusCode": 401, "body": json.dumps({"error": "Email atau password salah"})}

            user = users[0]
            stored = user['password_hash']
            salt, pw_hash = stored.split(':')

            check = hashlib.pbkdf2_hmac('sha256', password.encode(), salt.encode(), 100000).hex()
            if check != pw_hash:
                return {"statusCode": 401, "body": json.dumps({"error": "Email atau password salah"})}

            token = secrets.token_hex(32)
            supabase_request("sessions", "POST", {
                "user_id": user['id'], "token": token,
                "expires_at": time.strftime("%Y-%m-%dT%H:%M:%S+00:00", time.gmtime(time.time()+86400))
            })

            supabase_request("users?email=eq." + email, "PATCH", {
                "last_login": time.strftime("%Y-%m-%dT%H:%M:%S+00:00", time.gmtime())
            })

            return {"statusCode": 200, "headers": {"Access-Control-Allow-Origin": "*"}, "body": json.dumps({
                "success": True, "token": token,
                "user": {"email": email, "name": user['name'], "plan": user['plan']}
            })}

        return {"statusCode": 400, "body": json.dumps({"error": "Invalid action"})}

    except Exception as e:
        print(f"Error: {str(e)}")
        return {"statusCode": 500, "body": json.dumps({"error": "Internal server error"})}
'''

    os.makedirs(functions_dir, exist_ok=True)

    with open(os.path.join(functions_dir, 'auth.py'), 'w') as f:
        f.write(auth_code)
    print_ok("Created netlify/functions/auth.py")

    return True


# ============================================
# STEP 3: Update Frontend API URL
# ============================================
def update_frontend_api_url(netlify_url):
    print_step(3, "Update Frontend API URL")

    # Update pricing.html
    pricing_path = os.path.join(PROJECT_DIR, 'pricing.html')
    if os.path.exists(pricing_path):
        with open(pricing_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # Replace API_BASE
        content = content.replace(
            "const API_BASE = 'https://beebane25.iothub-api.netlify.app'",
            f"const API_BASE = '{netlify_url}'"
        )

        with open(pricing_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print_ok(f"Updated pricing.html → {netlify_url}")

    # Update js/app.js
    appjs_path = os.path.join(PROJECT_DIR, 'js', 'app.js')
    if os.path.exists(appjs_path):
        with open(appjs_path, 'r', encoding='utf-8') as f:
            content = f.read()

        content = content.replace(
            "API_BASE: 'https://beebane25.iothub-api.netlify.app'",
            f"API_BASE: '{netlify_url}'"
        )

        with open(appjs_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print_ok(f"Updated js/app.js → {netlify_url}")


# ============================================
# STEP 4: Test Connections
# ============================================
def test_connections(env):
    print_step(4, "Test Koneksi")

    # Test Supabase
    print_info("Testing Supabase connection...")
    try:
        from urllib.request import Request, urlopen
        url = f"{env['supabase_url']}/rest/v1/users?select=id&limit=1"
        req = Request(url, headers={
            'apikey': env['supabase_anon'],
            'Authorization': f"Bearer {env['supabase_anon']}"
        })
        with urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode())
            print_ok(f"Supabase connected! Users table: {len(data)} rows")
    except Exception as e:
        print_err(f"Supabase connection failed: {e}")

    # Test Netlify Functions (if URL provided)
    netlify_url = get_input("\nNetlify Functions URL (kosongkan jika belum deploy)", "")
    if netlify_url:
        print_info("Testing Netlify Functions...")
        try:
            from urllib.request import Request, urlopen
            req = Request(f"{netlify_url}/.netlify/functions/auth", headers={'Content-Type': 'application/json'})
            with urlopen(req, timeout=10) as resp:
                print_ok(f"Netlify Functions connected!")
        except Exception as e:
            print_info(f"Netlify test: {e} (normal jika belum deploy)")

    return netlify_url


# ============================================
# STEP 5: Generate Deployment Guide
# ============================================
def generate_deploy_guide(netlify_url, env):
    print_step(5, "Generate Deployment Guide")

    guide = f"""# IoTHub Deployment Guide

## Environment
- Frontend: https://beebane25.github.io/iothub/
- Backend: {netlify_url or '(belum deploy)'}
- Database: {env['supabase_url']}
- Payment: Midtrans (Sandbox)

## Quick Commands

### Deploy to Netlify:
```bash
cd "{PROJECT_DIR}"
netlify deploy --prod --dir=. --functions=netlify/functions
```

### Deploy to GitHub Pages:
```bash
cd "{PROJECT_DIR}"
git push origin main
```

### Run locally:
```bash
cd "{PROJECT_DIR}"
python server.py
# Buka http://localhost:8080
```

## Environment Variables (for Netlify)
```
SUPABASE_URL={env['supabase_url']}
SUPABASE_ANON_KEY={env['supabase_anon'][:20]}...
SUPABASE_SERVICE_KEY={env['supabase_service'][:20]}...
MIDTRANS_CLIENT_KEY={env['midtrans_client']}
MIDTRANS_SERVER_KEY={env['midtrans_server'][:20]}...
```

## Database Tables
1. users - Data akun
2. sessions - Sesi login
3. views - Log viewing
4. subscribers - Newsletter
5. articles - Metadata artikel
6. payments - Riwayat pembayaran

## API Endpoints
- POST /api/auth (action: register|login)
- POST /api/subscribe
- POST /api/subscribe (Midtrans webhook)

## Testing Checklist
- [ ] Register akun baru
- [ ] Login dengan akun baru
- [ ] Buka artikel premium (blocked)
- [ ] Buka artikel gratis (email gate)
- [ ] Upgrade ke premium (pricing page)
- [ ] Bayar dengan Midtrans (sandbox)
- [ ] Cek data di Supabase
"""

    guide_path = os.path.join(PROJECT_DIR, 'DEPLOY.md')
    with open(guide_path, 'w', encoding='utf-8') as f:
        f.write(guide)
    print_ok(f"Created DEPLOY.md")


# ============================================
# MAIN
# ============================================
def main():
    print("""
╔══════════════════════════════════════════════╗
║     IoTHub Full Setup Script                 ║
║     Setup Supabase + Netlify + Midtrans      ║
╚══════════════════════════════════════════════╝
    """)

    # Step 1: Environment Variables
    env = setup_env()

    # Step 2: Create Netlify Functions
    create_netlify_functions()

    # Step 3: Test connections
    netlify_url = test_connections(env)

    # Step 4: Update frontend
    if netlify_url:
        update_frontend_api_url(netlify_url)

    # Step 5: Generate deploy guide
    generate_deploy_guide(netlify_url, env)

    print(f"""
{'='*50}
  SETUP SELESAI!
{'='*50}

  Selanjutnya:
  1. Deploy ke Netlify:
     netlify deploy --prod --dir=. --functions=netlify/functions

  2. Update API URL di pricing.html & app.js

  3. Setup Midtrans webhook:
     https://dashboard.midtrans.com → Settings → Payment Notification

  4. Test seluruh sistem

  Lihat DEPLOY.md untuk panduan lengkap.
    """)


if __name__ == '__main__':
    main()
