[vars]
SUPABASE_URL = "https://nbungbznljbiddlwyvbd.supabase.co"
SUPABASE_SERVICE_KEY = "sb_publishable_XX4t1V_Ur7U82qmQW6HNkw_Y8kTtiTQ"
MIDTRANS_SERVER_KEY = "Mid-server-HCBkVMSxPouPg0Cm0vy5hlEa"
MIDTRANS_IS_PRODUCTION = "false"
