#!/usr/bin/env python3
"""
deep_check_mermaid.py — Deep check mermaid blocks for mermaid 11.16.0 compatibility.
Focuses on blocks generated by svg_to_mermaid.py (unquoted labels).
"""

import re
import html
import glob

def extract_mermaid_blocks(content):
    blocks = []
    pattern = re.compile(r'<pre\s+class="mermaid">\s*\n?(.*?)\s*</pre>', re.DOTALL)
    for match in pattern.finditer(content):
        code = html.unescape(match.group(1).strip())
        blocks.append(code)
    return blocks


def check_block(code, fname, block_idx):
    """Deep check a single mermaid block."""
    issues = []
    lines = code.split('\n')
    
    for i, line in enumerate(lines, 1):
        stripped = line.strip()
        if not stripped or stripped.startswith('%'):
            continue
        
        # Skip non-node lines
        if stripped.startswith(('flowchart', 'graph', 'style', 'subgraph', 'end', 'direction')):
            continue
        
        # Check unquoted labels: N0[text here]
        # These break if text contains special chars
        unquoted_matches = re.findall(r'\w+\[(.+?)\]', stripped)
        for label in unquoted_matches:
            # Skip if it starts with " (quoted) or / (stadium)
            if label.startswith('"') or label.startswith('/'):
                continue
            
            # Check for problematic chars in unquoted labels
            bad_chars = []
            for ch in ['#', '{', '}', '(', ')', '[', ']', '"', "'", '<', '>', '&', '|', ';']:
                if ch in label:
                    bad_chars.append(ch)
            
            if bad_chars:
                issues.append(f"L{i}: Unquoted label with {bad_chars}: '{label[:60]}'")
        
        # Check unquoted in stadium: N0[/text here/]
        unquoted_stadium = re.findall(r'\[/(.+?)/\]', stripped)
        for label in unquoted_stadium:
            if label.startswith('"'):
                continue
            bad_chars = []
            for ch in ['#', '{', '}', '(', ')', '[', ']', '"', "'", '<', '>', '&', '|', ';']:
                if ch in label:
                    bad_chars.append(ch)
            if bad_chars:
                issues.append(f"L{i}: Unquoted stadium with {bad_chars}: '{label[:60]}'")
        
        # Check unquoted in diamond: N0{text here}
        unquoted_diamond = re.findall(r'\w+\{(.+?)\}', stripped)
        for label in unquoted_diamond:
            if label.startswith('"'):
                continue
            bad_chars = []
            for ch in ['#', '(', ')', '[', ']', '"', "'", '<', '>', '&', '|', ';']:
                if ch in label:
                    bad_chars.append(ch)
            if bad_chars:
                issues.append(f"L{i}: Unquoted diamond with {bad_chars}: '{label[:60]}'")
        
        # Check for • character (bullet) - may cause issues
        if '•' in stripped:
            issues.append(f"L{i}: Bullet char '•': '{stripped[:60]}'")
        
        # Check for emoji that might break
        emoji_pattern = re.compile(r'[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F1E0-\U0001F1FF]')
        if emoji_pattern.search(stripped):
            # Emojis in mermaid can be problematic
            pass  # Usually OK, skip
    
    return issues


def main():
    files = sorted(glob.glob('articles/*.html'))
    
    total_blocks = 0
    total_issues = 0
    files_with_issues = []
    
    for fpath in files:
        content = open(fpath, encoding='utf-8').read()
        blocks = extract_mermaid_blocks(content)
        
        if not blocks:
            continue
        
        file_issues = []
        for j, block in enumerate(blocks):
            total_blocks += 1
            issues = check_block(block, fpath, j)
            for issue in issues:
                file_issues.append(f"  Block {j+1}: {issue}")
                total_issues += 1
        
        fname = fpath.replace('\\', '/').split('/')[-1]
        if file_issues:
            files_with_issues.append(fname)
            print(f"\n⚠️  {fname} ({len(file_issues)} issues)")
            for issue in file_issues[:15]:
                print(f"  {issue}")
            if len(file_issues) > 15:
                print(f"  ... and {len(file_issues) - 15} more")
    
    print(f"\n{'='*60}")
    print(f"Files checked:      {len(files)}")
    print(f"Total mermaid:      {total_blocks}")
    print(f"Total issues:       {total_issues}")
    print(f"Files with issues:  {len(files_with_issues)}")


if __name__ == '__main__':
    main()
